apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: langy-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jessicadraper/devops-5-iac.git
    path: k8s/overlays/prod
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: devops5-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
