apiVersion: apps/v1
kind: Deployment
metadata:
  name: langy
spec:
  replicas: 1 # Number of pod replicas to run
  template:
    spec:
      containers:
      - name: langy-container
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: langy-service
spec:
  ports:
  - port: 80 # The port that the Service will expose inside the cluster
    nodePort: 30095 # The port on the node that will proxy to the service port
