apiVersion: apps/v1
kind: Deployment
metadata:
  name: langy
spec:
  replicas: 2 # Number of pod replicas to run
  selector:
    matchLabels:
      app: langy
  template:
    metadata:
      labels:
        app: langy
    spec:
      containers:
      - name: langy-container
        image: ghcr.io/jessicadraper/langy:v1
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: langy-service
spec:
  ports:
    nodePort: 30095 # The port on the node that will proxy to the service port
  selector:
    app: langy

