apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-sa 
  namespace: devops5
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: devops5
  name: devops-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-role-binding
  namespace: devops5
subjects:
- kind: ServiceAccount
  name: devops-sa
  namespace: devops5
roleRef:
  kind: Role
  name: devops-role
  apiGroup: rbac.authorization.k8s.io