- name: Provision Ubuntu VM with Kubernetes and security  hardening
  hosts: vm
  become: true
  tasks:

    - name: Update and upgrade packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - "curl"
          - "gnupg"
          - "software-properties-common"
          - "ufw"
          - "auditd"
          - "unattended-upgrades"
          - "python3-pip"
        state: present

    - name: Download K3s install script
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /tmp/install-k3s.sh
        mode: '0755'

    - name: Run K3s install script
      ansible.builtin.command: /tmp/install-k3s.sh
      args:
        creates: /usr/local/bin/k3s

    - name: Disable root SSH login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
      notify: Restart SSH

    - name: Set up audit logging
      ansible.builtin.service:
        name: auditd
        state: started
        enabled: true

    - name: Enable automatic security updates
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        content: |
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Unattended-Upgrade "1";
        owner: root
        group: root
        mode: '0644'

    - name: Set UFW firewall
      community.general.ufw:
        direction: incoming
        policy: deny

    - name: Allow SSH
      community.general.ufw:
        rule: allow
        port: 22
        proto: tcp

    - name: Allow HTTP
      community.general.ufw:
        rule: allow
        port: 80
        proto: tcp

    - name: Allow HTTPS
      community.general.ufw:
        rule: allow
        port: 443
        proto: tcp

    - name: Enable UFW
      community.general.ufw:
        state: enabled

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: ssh
        state: restarted
