apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-sa 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devops-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-role-binding
subjects:
- kind: ServiceAccount
  name: devops-sa
roleRef:
  kind: Role
  name: devops-role
  apiGroup: rbac.authorization.k8s.io