name: CI K8s Lint

on:
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
  pull-requests: write

jobs:
  kube-linter:
    name: Kube Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run kube-linter
        uses: stackrox/kube-linter-action@v1
        with:
          directory: k8s